Dintero/Dintero.Checkout.WooCommerce

- dintero-hp/README.md
- dintero-hp/changelog.txt
- dintero-hp/dintero-hp.php
- dintero-hp/includes/class-wc-dintero-hp-ajax.php
- dintero-hp/includes/class-wc-dintero-hp-checkout.php
- dintero-hp/includes/class-wc-dintero-hp.php
2020.12.14
* Shipping address required field issue
* Update order meta-data in callback
> Update order metadata in callback

- README.md
- assets/css/style.css
- assets/js/checkout.js
- changelog.txt
- dintero-hp.php
- includes/class-wc-dintero-hp-checkout.php
- includes/class-wc-dintero-hp.php
- includes/class-wc-gateway-dintero-hp.php
2021.02.10
* Rounding error fix
* Css fix for the redirected payment order review
* Session lock removed from on session load
* Css fix for Cart Mini
* Branding image on checkout issue
> Version 2021.02.10

- README.md
- README.txt
- changelog.txt
- dintero-hp.php
- includes/class-wc-dintero-hp-checkout.php
2021.02.15
* Fix VAT rounding error
> Fix VAT rounding error

- README.md
- README.txt
- changelog.txt
- dintero-hp.php
- includes/class-wc-dintero-hp-checkout.php
- includes/class-wc-gateway-dintero-hp.php
2021.02.27
* Setting to limit customer types
> Settings for limiting customer types

- .editorconfig
- assets/css/style.css
- includes/class-wc-dintero-hp-checkout.php
- includes/class-wc-dintero-hp.php
When session creation fails, do the following:
- Give request_id to user for easier error handling
- Log more info to JavaScript console
> Show indication that checkout failed to load

- includes/class-wc-dintero-hp-checkout.php
- includes/class-wc-gateway-dintero-hp.php
Add note on order if captures or refunds fail.
> Note when captures and refunds fail

- assets/css/global-style.css
- assets/css/style.css
- includes/class-wc-dintero-hp.php
Add global style for dintero branding
> Center Dintero branding

- README.md
- README.txt
- changelog.txt
- dintero-hp.php
2021.03.10
* Setting to allow orders without shipping
* Error messages when API calls fail
> Release 2021.03.10

- README.md
- README.txt
- changelog.txt
- dintero-hp.php
- includes/class-wc-dintero-hp-ajax.php
- includes/class-wc-dintero-hp-checkout.php
2021.03.22
* Bugfix: Fix problem with logged in accounts
> Release 2021.03.22

- README.md
- README.txt
- changelog.txt
- dintero-hp.php
- includes/class-wc-dintero-hp-checkout.php
2021.03.24
* Bugfix: Fix country code issue
> Release 2021.03.24

- README.md
- README.txt
- changelog.txt
- dintero-hp.php
- includes/class-wc-dintero-hp.php
2021.03.26
* Redirect to cart on failed payment
> Redirect to cart on failed payment

- README.md
- README.txt
- changelog.txt
- dintero-hp.php
- includes/class-wc-gateway-dintero-hp.php
2021.03.30
* Pay for Order issue fix
> Create order from admin

- assets/js/checkout.js
2021.05.26
* Bugfix: #47 fixed some cases of other payment methods not working with Dintero. This fixes the rest.
> Fix other payment methods when Dintero is sorted first

- dintero-hp.php
- includes/class-dintero-hp-adapter.php
- includes/class-dintero-hp-request-builder.php
- includes/class-dintero-hp-request.php
- includes/class-wc-dintero-hp-ajax.php
- includes/class-wc-dintero-hp-checkout.php
Use WooCommerce sessions table to initiate order created from callback
- Improve order creation with coupons
- Fix bug with different tax zone
> Move order creation for embedded express sessions

- README.txt
- dintero-hp.php
- includes/class-dintero-hp-adapter.php
- includes/class-wc-dintero-hp-ajax.php
- includes/class-wc-dintero-hp-checkout.php
- includes/class-wc-dintero-hp.php
- includes/class-wc-gateway-dintero-hp.php
2021.06.21
* Add option of having a Checkout Express button on the product pages
* Bugfix: Populate Checkout Express session with user details
Closes #46
> Populate Checkout Express-session with customer data

- README.txt
- dintero-hp.php
2021.07.06
* Fixed decimals in shipping option amount
* Update order status on callback if current status is pending
> Release v2021.07.06

- includes/class-wc-dintero-hp.php
Fix css for repeating Checkout Express button
> Fix double Checkout Express button 

- README.txt
- dintero-hp.php
* Fix issue where the wrong shipping title was displayed when order was created from callback
* Fix issue with multiple Checkout Express buttons
* Fix issues where VAT is set with two extra zeros
* Improvements on batch captures, so more batch captures will complete. If it still doesn't, a note describing the reason will be added.
> Release 2021.08.09

- README.txt
- dintero-hp.php
- includes/class-wc-gateway-dintero-hp.php
Release 2021-08-12
* Fix issue where the wrong shipping title was displayed when order was created from callback
* Fix issue with multiple Checkout Express buttons
* Fix issues where VAT is set with two extra zeros
* Improvements on batch captures, so more batch captures will complete. If it still doesn't, a note describing the reason will be added.
> Release 2021-08-12

- README.md
- README.txt
- dintero-hp.php
- includes/class-wc-dintero-hp-ajax.php
- tests/phpunit/test-ajax.php
> Fix issue with ON_HOLD after order is pending

- README.txt
- dintero-hp.php
* Fix issue with missing metadata when creating order via callback
> Release 2021.08.19

- README.txt
- dintero-hp.php
- includes/class-wc-dintero-hp-ajax.php
- includes/class-wc-dintero-hp-checkout.php
- includes/class-wc-dintero-hp-helper.php
- includes/class-wc-dintero-hp.php
- includes/class-wc-gateway-dintero-hp.php
- tests/manual/shipping_in_iframe.md
- tests/phpunit/helpers/class-wc-helper-order.php
- tests/phpunit/test-ajax.php
- tests/phpunit/test-class-wc-dintero-hp-checkout.php
- tests/phpunit/test-class-wc-gateway-dintero-hp.php
- Fixes double shipping options in checkout when shipping options not in iframe
- Fixes cent-difference in redirect-mode
- Fixes capture problem when line_id is wrong
- Decreases number of updates when shipping in iframe
- Adds note when capture not attempted because of diverging amounts
> Fix shipping_option problems

- README.txt
- includes/class-wc-dintero-hp-checkout.php
- includes/class-wc-dintero-hp-helper.php
- includes/class-wc-gateway-dintero-hp.php
- tests/phpunit/test-class-wc-dintero-hp-helper.php
- tests/phpunit/test-class-wc-gateway-dintero-hp.php
Populate `session.order.store.id` with the webshop url to filter on it in Dintero.
> Set store based on webshop url

- README.txt
- dintero-hp.php
- includes/class-wc-dintero-hp-checkout.php
- includes/class-wc-dintero-hp-helper.php
- includes/class-wc-dintero-hp.php
- tests/phpunit/helpers/class-wc-helper-product.php
- tests/phpunit/test-class-wc-dintero-hp-checkout.php
- tests/phpunit/test-class-wc-dintero-hp-helper.php
- Fix cent difference in session initialization
- Add partially captured-status to order list
> Fix cent difference in session initialization

- README.txt
- dintero-hp.php
2021.11.22
* Fix bug in shipping address-callback introduced in 2021.11.17. Affected some merchants with shipping in iframe.
> Release 2021.11.22

- README.txt
- dintero-hp.php
* Allow capture even if merchant_reference doesn't match
> Release 2021.11.29

- README.txt
- dintero-hp.php
2022.01.03
* Fix edge-case rounding issue with certain discount codes
* Fix issues with PHP 8
* Remove dangling commas in function calls to better support PHP 7.2
> Release 2022.01.03

- README.txt
- dintero-hp.php
- includes/class-wc-dintero-hp-checkout.php
2022.01.05
* Rollback rounding fix from 2022.01.03 that caused problems for some stores
> rollback rounding fix

- README.txt
- composer.json
- composer.lock
- dintero-hp.php
- phpunit.xml.dist
- tests/phpunit/test-ajax.php
- tests/phpunit/test-class-wc-dintero-hp-checkout.php
- tests/phpunit/test-class-wc-dintero-hp-helper.php
- tests/phpunit/test-class-wc-gateway-dintero-hp.php
* Increase request timeout
* Added hook to change items before creating session
Upgraded from phpunit 7 to 9 because of deprecations making trouble for unit tests
> 2022.02.09

- includes/class-wc-gateway-dintero-hp.php
- tests/phpunit/test-class-wc-gateway-dintero-hp.php
Adding this to see if it might prevent issues with 403 when receiving the callback
Ref https://github.com/Dintero/operation/issues/904
> Add 10 second delay for callback_url for redirect-sessions

- README.txt
- dintero-hp.php
* Add delay before sending callback after successful transaction
> Release 2022.02.28

- README.txt
- dintero-hp.php
- includes/class-wc-dintero-hp.php
- Remove "Not Dintero"-text from Dintero-status column
- Release info for 2022.03.22
> remove not dintero
